package com.mentatlabs.nsa
package experimental_dsl

trait ExperimentalDSL {
  object adapted
  object analysis
  object any
  object args
  object assertions
  object by
  object calls
  object classfile
  object code
  object conversions
  object dead
  object debug
  object discard
  object elim
  object expand
  object forwarders
  object free
  object handlers
  object `implicit`
  object implicit_conversions
  object implicits
  object `import`
  object inaccessible
  object infer
  object inference
  object keeps
  object lite
  object lubs
  object name
  object nullary
  object nullary_override
  object numeric
  object opt
  object `override`
  object patmat
  object pos
  object prevention
  object reflective
  object specialization
  object star
  object sync
  object terms
  object types
  object uescape
  object unit
  object unreachable
  object unused
  object unused_import
  object value
  object warnings
  object widen
}
