package hr.element.nsa
package experimental_dsl

trait ScalacOptions
    extends ScalacCoreOptions
    with ScalacAdvancedOptions
    with ScalacPrivateOptions

trait ScalacCoreOptions
    extends DeprecationDSL
    with EncodingDSL
    with ExplaintypesDSL
    with FeatureDSL
    with GDSL
    with HelpDSL
    with LanguageDSL
    with NoDSL
    with NobootcpDSL
    with NowarnDSL
    with OptimiseDSL
    with PrintDSL
    with TargetDSL
    with UncheckedDSL
    with UniqidDSL
    with VerboseDSL

trait ScalacAdvancedOptions
    extends XDSL
    with XcheckinitDSL
    with XlintDSL
    with XlogDSL
    with XmaxDSL
    with XnoDSL
    with XnojlineDSL
    with XprintDSL
    with XpromptDSL
    with XresidentDSL
    with XstrictDSL
    with XverifyDSL

trait ScalacPrivateOptions
    extends YDSL
    with YclosureDSL
    with YconstDSL
    with YdeadDSL
    with YdebugDSL
    with YdisableDSL
    with YinlineDSL
    with YmacroDSL
    with YreplDSL
    with YwarnDSL
