package hr.element.sbt.nsa
package dsl

object adapted
object any
object args
object classfile
object code
object dead
object discard
object handlers
object `import`
object inaccessible
object infer
object name
object nullary
object nullary_override
object numeric
object `override`
object unit
object unused
object unused_import
object value
object warnings
object widen
