package com.mentatlabs.nsa
package scalac
package dsl

import experimental._

trait ScalacOptionsExperimentalDSL
    extends ScalacExperimentalDSL

    // core options experimental
    with ScalacDeprecationDSL
    with ScalacEncodingDSL
    with ScalacExplaintypesDSL
    with ScalacFeatureDSL
    with ScalacGDSL
    with ScalacHelpDSL
    with ScalacLanguageDSL
    with ScalacNobootcpDSL
    with ScalacNoDSL
    with ScalacNowarnDSL
    with ScalacOptimiseDSL
    with ScalacPrintDSL
    with ScalacSourcepathDSL
    with ScalacTargetDSL
    with ScalacUncheckedDSL
    with ScalacUniqidDSL
    with ScalacUsejavacpDSL
    with ScalacUsemanifestcpDSL
    with ScalacVerboseDSL
    with ScalacVersionDSL
    with ScalacXDSL

    // advanced options experimental
    with ScalacXCheckinitDSL
    with ScalacXDevDSL
    with ScalacXDisableDSL
    with ScalacXElideDSL
    with ScalacXExperimentalDSL
    with ScalacXFatalDSL
    with ScalacXFullDSL
    with ScalacXFutureDSL
    with ScalacXLintDSL
    with ScalacXLogDSL
    with ScalacXMaxDSL
    with ScalacXNoDSL
    with ScalacXNojlineDSL
    with ScalacXPluginDSL
    with ScalacXPrintDSL
    with ScalacXPromptDSL
    with ScalacXResidentDSL
    with ScalacXShowDSL
    with ScalacXSourceDSL
    with ScalacXStrictDSL
    with ScalacXVerifyDSL
    with ScalacYDSL

    // private additional experimental
    with ScalacYBackendDSL
    with ScalacYBreakDSL
    with ScalacYClosureDSL
    with ScalacYCompactDSL
    with ScalacYConstDSL
    with ScalacYDeadDSL
    with ScalacYDebugDSL
    with ScalacYDelambdafyDSL
    with ScalacYDisableDSL
    with ScalacYDocDSL
    with ScalacYEtaDSL
    with ScalacYIdeDSL
    with ScalacYInferDSL
    with ScalacYInlineDSL
    with ScalacYIssueDSL
    with ScalacYLogDSL
    with ScalacYMacroDSL
    with ScalacYNoDSL
    with ScalacYNooptimiseDSL
    with ScalacYOptDSL
    with ScalacYOverrideDSL
    with ScalacYPatmatDSL
    with ScalacYPosDSL
    with ScalacYPresentationDSL
    with ScalacYQuasiquoteDSL
    with ScalacYRangeposDSL
    with ScalacYReifyDSL
    with ScalacYReplDSL
    with ScalacYResolveDSL
    with ScalacYShowDSL
    with ScalacYSkipDSL
    with ScalacYStatisticsDSL
    with ScalacYStopDSL
    with ScalacYTyperDSL
    with ScalacYWarnDSL
